### ISSUE TITLE
Thales has an incorrect description

### ISSUE THREAD

**Issue by JoeyPriceless** [S4N0I/theschoolofathens#1]
When clicking on Thales of Miletus, it shows the description of the River Thames's wikipedia article.

Looking at scrape/pretty.json, it seems like any time the scrape data only specifies "Thales", it is given the incorrect pageid (49031) while references using "Thales of Miletus" have the correct one (30072).

Maybe this is an error caused by the wikipedia.page() assuming you mean Thames when not using the full name?

**Comment by jackdcasey** [comment]
Working on it!

**Comment by computerfachmann** [comment]
Wow, thanks for creating the issue @JoeyPriceless and thanks for the quick patch @jackdcasey. I will deploy the change to the live version shortly.
